### ISSUE TITLE
maybe a small touch is needed for AWS account id?

### ISSUE THREAD

**Issue by tirelibirefe** [aws-samples/docker-ecr-actions-workflow#5]
Hello,
Great walkthrough.

..but maybe a small touch is needed.
![image](https://github.com/aws-samples/docker-ecr-actions-workflow/assets/45227339/6a081509-92d2-4dc7-bd45-128a3b4bd320)

**Comment by rmodi1** [comment]
Thank you @tirelibirefe for bringing this to my notice. I will update the solution with a fix for this soon.

**Comment by ruchimo** [comment]
I have updated the pre-requisites with the link on how this can be configured
